import "./jquery";
import "./jquery.client";
import "./jquery.textSelection";
import "./mediawiki";
import "./mediawiki.api";
import "./mediawiki.base";
import "./mediawiki.cldr";
import "./mediawiki.cookie";
import "./mediawiki.experiments";
import "./mediawiki.ForeignApi";
import "./mediawiki.ForeignApi.core";
import "./mediawiki.jqueryMsg";
import "./mediawiki.language";
import "./mediawiki.language.months";
import "./mediawiki.libs.pluralruleparser";
import "./mediawiki.notification";
import "./mediawiki.storage";
import "./mediawiki.String";
import "./mediawiki.template";
import "./mediawiki.Title";
import "./mediawiki.Uri";
import "./mediawiki.user";
import "./mediawiki.util";
import "./mediawiki.visibleTimeout";

export = mw;
